### ISSUE TITLE
Environment not recognised for mypy, but is for jedi

### ISSUE THREAD

**Issue by alxdb** [Richardk2n/pylsp-mypy#16]
Hi, I have added this plugin to the main server (`python-lsp-server`) which I have installed via pipx:

```shell
pipx install python-lsp-server
pipx inject python-lsp-server pylsp-mypy
```

I have created a virtual environment and am directing the server to use it via `plugins.jedi.environment` and I have also tried running the server in the virtual environment (although it is not installed there).

Both methods work for jedi services (code completion, documentation, etc) but when using the mypy checks, libraries with type stubs installed are always flagged as errors of type `missing imports`. This does not occur when running mypy from the environment.

Not sure if this is a known issue or there's some configuration I'm missing, seems strange to me that the jedi part of the server picks up the environment, but the mypy part does not.

Any help would be very much appreciated!

**Comment by StabbarN** [comment]
Have you set the command path in your sublime project:
```
        "LSP": {
            "pylsp": {
                "enabled": true,
                "command": [
                    ".../.venv/bin/pylsp",
                ],
```
?

**Comment by alxdb** [comment]
I'm using [Doom Emacs](https://github.com/hlissner/doom-emacs) as my editor, not Sublime Text. Additionally, I'm using a globally installed version of pylsp, rather than one installed in a local virtualenv. For what it's worth, the equivalent emacs config variable is `lsp-pylsp-server-command` and it is set to `pylsp` in my configuration (which is the default value).

**Comment by jpneverwas** [comment]
IIRC, questions like this were sort of asked/answered a year or two ago in the abandoned forerunner project. Too bad GitHub doesn't integrate searches and references somehow. (Or... they probably do and I'm just old/dumb.)

Anyway, OP, if you still use this plugin, please try this patch.

Install globally (just a guess, haven't used pipx in forever):
```console
$ pipx inject python-lsp-server git+https://github.com/jpneverwas/pylsp-mypy@overrides
```

Add some init (if doom doesn't already have something for this):
```lisp
(defvar-local my/lsp/custom-settings nil)
(put 'my/lsp/custom-settings 'safe-local-variable #'vectorp)

(defun my/on-hack-locals ()
  (when my/lsp/custom-settings
    (lsp-register-custom-settings my/lsp-custom-settings)))

(defun my/on-prog-mode ()
  (add-hook 'hack-local-variables-hook #'my/on-hack-locals nil t))

(add-hook 'prog-mode-hook #'my/on-prog-mode)

;; BTW, I find this -v flag quite useful for debugging lsp-mode
(set-variable 'lsp-pylsp-server-command '("pylsp" "-v"))
```

And then the usual `~/proj/.dir-locals.el`:
```lisp
((python-mode
  . ((my/lsp/custom-settings
      ("pylsp.plugins.pylsp_mypy.enabled" t t)
      ("pylsp.plugins.pylsp_mypy.live_mode" nil t)
      ("pylsp.plugins.pylsp_mypy.dmypy" t t)
      ("pylsp.plugins.pylsp_mypy.overrides"
       ["--python-executable" "/home/user/proj/.venv/bin/python" t]))
     ;; in case you switched to eglot
     (eglot-workspace-configuration
      . ((:pylsp . (:plugins
                    (:pylsp_mypy
                     (:enabled t
                      :live_mode nil
                      :dmypy t
                      ;; last I checked (like 1+ yrs ago w. pyls),
                      ;; a bug in eglot made config-file necessary
                      :overrides ["--config-file"
                                  "/home/user/proj/mypy.ini"
                                  "--python-executable"
                                  "/home/user/proj/.venv/bin/python"
                                  t]))))))
     (lsp-pylsp-plugins-jedi-environment . "/home/user/proj/.venv"))))
```

I probably botched a few things, but you get the idea. Let me know what
happens. (Emacs FTW!)

**Comment by Richardk2n** [comment]
This is likely fixed by now. Please test.

**Comment by Richardk2n** [comment]
Closing because no reply is assumed to mean it is fixed
